const w=(s:string)=>s.split(' ')
export const WORDS:Record<string,string[]>={
Food:w('APPLE PIZZA BANANA SUSHI BURGER PASTA COOKIE CHEESE NOODLES MANGO PANCAKE TACO CARROT POPCORN CHOCOLATE SANDWICH WATERMELON OMELETTE'),
Animals:w('TIGER ELEPHANT PENGUIN GIRAFFE DOLPHIN KANGAROO BUTTERFLY OCTOPUS RABBIT CROCODILE OWL MONKEY SHARK PEACOCK TURTLE SPIDER HORSE BEE'),
Objects:w('UMBRELLA KEYBOARD BACKPACK SCISSORS MIRROR CANDLE LADDER PILLOW CAMERA WALLET HAMMER BALLOON TOOTHBRUSH CLOCK GUITAR BICYCLE LANTERN BOTTLE'),
Places:w('BEACH AIRPORT LIBRARY HOSPITAL MUSEUM TEMPLE VOLCANO CASTLE FOREST DESERT STADIUM MARKET BRIDGE ISLAND CINEMA FARM HOTEL WATERFALL'),
Movies:w('TITANIC AVATAR INCEPTION FROZEN SHREK JAWS MATRIX GLADIATOR COCO ALADDIN PSYCHO ROCKY GODZILLA UP JOKER MULAN BARBIE DUNE'),
Everyday:w('BREAKFAST SHOWER ALARM TRAFFIC ELEVATOR HOMEWORK BIRTHDAY HOLIDAY SHOPPING LAUNDRY PASSWORD TRAIN WEDDING NAPPING COFFEE RAIN SELFIE PICNIC')}
